<?php
/** @file
 * Implement the cupcake module.
 */

/**
 * Implementation of hook_theme().
 */
function cupcake_theme()
{
  return array(
    'cupcake' => array(
      'arguments' => array(),
      'function' => 'theme_cupcake',
    ),
  );
}

function theme_cupcake()
{
  return '<div id="cupcake" style="#cupcake{min-width:200px}"><iframe src="//crypto.stanford.edu/flashproxy/embed.html" width="80" height="15" frameborder="0" scrolling="no"></iframe><a href="https://crypto.stanford.edu/flashproxy/">[info]</a><a href="https://crypto.stanford.edu/flashproxy/options.html">[options]</a></div>';
}

function cupcake_footer()
{
  return theme('cupcake');
}